name: Main

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2  
      - name: cfn-lint
        uses: softprops/cfn-lint-action@problem-matchers
        with:
          args: '**/*.cf.yml'