name: Main

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Problem Matchers
        run: |
          echo "::add-matcher::cfn-lint.json"   
      - name: cfn-lint
        uses: scottbrenner/cfn-lint-action@master
        with:
          args: '**/*.cf.yml'